### ISSUE TITLE
No music / no cutscene sound TR2X linux

### ISSUE THREAD

**Issue by Toumlab** [LostArtefacts/TRX#2504]
Error msg example: 
game/music/music_main.c 135 Music_Play Not playing track 58 because no backend is available

fmv sound is fine, as well as in-game sounds...

The same applies to TRX2x version 0.8 (and I tried a bunch of unreleased assets!)

Funny fact: in TR2X_gameflow.json5 we can see:
    "title": {
        "path": "data/title.tr2",
        "music_track": 64,

->Tracks are supposed to be from track02 to track 61!!

**Comment by rr-** [comment]
@Toumlab thanks, for reasons unknown to me, the track have different IDs than filenames (and that is the expected, OG-compatible behavior).

@LostArtefacts/dev @LostArtefacts/qa can I ask to provide an instruction how to install music assets, and possibly a PR to covert his topic in `docs/tr2/README.md`?

**Comment by Toumlab** [comment]
All my music tracks are .flac files.
it works fine with TR1X, not in TR2X for some reason.

**Comment by o-schneider** [comment]
Ambient/music tracks are not played on my end either with the Linux build. It looks for tracks that are not existing in my GOG release, maybe there's some installation step missing?
The log I have (it's the track for the Great Wall)
```
game/music/music_main.c 141 Music_Play Playing track 64 (real: 60), mode: 1
libtrx/engine/audio_stream.c 354 M_InitialiseFromPath Error while opening audio music/60.flac: No such file or directory
game/music/music_main.c 146 Music_Play Failed to create music stream for track 64
```
The music directory content from the GOG release:
```
57.mp3       Track06.ogg  Track11.ogg  Track16.ogg  Track21.ogg  Track26.ogg  Track31.ogg  Track36.ogg  Track41.ogg  Track46.ogg  Track51.ogg  Track56.ogg  Track61.ogg
Track02.ogg  Track07.ogg  Track12.ogg  Track17.ogg  Track22.ogg  Track27.ogg  Track32.ogg  Track37.ogg  Track42.ogg  Track47.ogg  Track52.ogg  Track57.ogg
Track03.ogg  Track08.ogg  Track13.ogg  Track18.ogg  Track23.ogg  Track28.ogg  Track33.ogg  Track38.ogg  Track43.ogg  Track48.ogg  Track53.ogg  Track58.ogg
Track04.ogg  Track09.ogg  Track14.ogg  Track19.ogg  Track24.ogg  Track29.ogg  Track34.ogg  Track39.ogg  Track44.ogg  Track49.ogg  Track54.ogg  Track59.ogg
Track05.ogg  Track10.ogg  Track15.ogg  Track20.ogg  Track25.ogg  Track30.ogg  Track35.ogg  Track40.ogg  Track45.ogg  Track50.ogg  Track55.ogg  Track60.ogg
```

**Comment by rr-** [comment]
@o-schneider what if you rename the tracks to lowercase? We do have a code in place to handle the casing on case-sensitive filesystems, but we also had reports that it does not work on certain machines.

**Comment by rr-** [comment]
Actually never mind. This is a bug and will be fixed shortly.

**Comment by rr-** [comment]
Fixed in #2509 which will be shortly available in a dev snapshot; in the meantime the recommended fix is to drop the `Track` prefix and name the files `60.ogg` by hand. I apologize for the inconvenience.

**Comment by Toumlab** [comment]
Hi!
I don't think this will change anything for me as I don't think my problem is in opening the music files, but rather in finding a proper backend to play these files ('game/music/music_main.c 135 Music_Play Not playing track 58 because no backend is available'). 
Thanks for your help!

**Comment by rr-** [comment]
@Toumlab there are three versions of the game that I'm aware of –

1) One that has numbered .flac / .ogg / .mp3 files inside a `music/` directory,
2) Another that has an `audio/cdaudio.dat` index file and a big `audio/cdaudio.wav` / `.mp3` continuous audio file,
3) And another one that has the music encoded on a physical disc.

Currently we support only the first two. LMK if this is of any help.

**Comment by Toumlab** [comment]
@rr I have version 1 (music directory).
I tried the very latest asset (TR2X 0.9.1) to no avail: 'no backend is available' error msg still shows... and no music is playing...

**Comment by rr-** [comment]
@Toumlab can I see output of `find` or similar from the game root directory?

**Comment by Toumlab** [comment]
This is my TR2X.log file

[TR2X.log](https://github.com/user-attachments/files/18812722/TR2X.log)

**Comment by rr-** [comment]
Thanks, however I was hoping more for a listing of all files in the game directory, as the logs in the present form do not present much information.

**Comment by Toumlab** [comment]
Sorry for the inconvenience, here is the list!
TR2X/cfg/TR2X_console_history.json5
TR2X/cfg/TR2X_gameflow.json5
TR2X/cfg/TR2X.json5
TR2X/cfg/TR2X_strings.json5
TR2X/data/ASSAULT.TR2
TR2X/data/BOAT.TR2
TR2X/data/catacomb.TR2
TR2X/data/credit01.PCX
TR2X/data/credit02.PCX
TR2X/data/credit03.PCX
TR2X/data/credit04.PCX
TR2X/data/credit05.PCX
TR2X/data/credit06.PCX
TR2X/data/credit07.PCX
TR2X/data/credit08.PCX
TR2X/data/CREDIT09.PCX
TR2X/data/CUT1.TR2
TR2X/data/cut2.TR2
TR2X/data/cut3.TR2
TR2X/data/cut4.TR2
TR2X/data/deck.TR2
TR2X/data/Emprtomb.tr2
TR2X/data/FLOATING.TR2
TR2X/data/house.TR2
TR2X/data/icecave.TR2
TR2X/data/injections/barkhang_itemrots.bin
TR2X/data/injections/catacombs_fd.bin
TR2X/data/injections/catacombs_itemrots.bin
TR2X/data/injections/deck_itemrots.bin
TR2X/data/injections/diving_itemrots.bin
TR2X/data/injections/floating_fd.bin
TR2X/data/injections/floating_itemrots.bin
TR2X/data/injections/house_itemrots.bin
TR2X/data/injections/opera_fd.bin
TR2X/data/injections/opera_itemrots.bin
TR2X/data/injections/palace_fd.bin
TR2X/data/injections/palace_itemrots.bin
TR2X/data/injections/rig_itemrots.bin
TR2X/data/injections/tibet_fd.bin
TR2X/data/injections/tibet_itemrots.bin
TR2X/data/injections/wall_itemrots.bin
TR2X/data/injections/wreck_fd.bin
TR2X/data/injections/wreck_itemrots.bin
TR2X/data/injections/xian_fd.bin
TR2X/data/injections/xian_itemrots.bin
TR2X/data/keel.TR2
TR2X/data/legal.PCX
TR2X/data/living.TR2
TR2X/data/MAIN.SFX
TR2X/data/MONASTRY.TR2
TR2X/data/OPERA.TR2
TR2X/data/platform.TR2
TR2X/data/RIG.TR2
TR2X/data/SKIDOO.TR2
TR2X/data/TITLE.PCX
TR2X/data/TITLE.tr2
TR2X/data/tombpc.dat
TR2X/data/unwater.TR2
TR2X/data/venice.TR2
TR2X/data/WALL.TR2
TR2X/data/xian.TR2
TR2X/fmv/ancient.rpl
TR2X/fmv/crash.rpl
TR2X/fmv/END.RPL
TR2X/fmv/jeep.rpl
TR2X/fmv/landing.rpl
TR2X/fmv/logo.rpl
TR2X/fmv/Modern.rpl
TR2X/fmv/ms.rpl
TR2X/music/57.mp3
TR2X/music/track02.flac
TR2X/music/track03.flac
TR2X/music/track04.flac
TR2X/music/track05.flac
TR2X/music/track06.flac
TR2X/music/track07.flac
TR2X/music/track08.flac
TR2X/music/track09.flac
TR2X/music/track10.flac
TR2X/music/track11.flac
TR2X/music/track12.flac
TR2X/music/track13.flac
TR2X/music/track14.flac
TR2X/music/track15.flac
TR2X/music/track16.flac
TR2X/music/track17.flac
TR2X/music/track18.flac
TR2X/music/track19.flac
TR2X/music/track20.flac
TR2X/music/track21.flac
TR2X/music/track22.flac
TR2X/music/track23.flac
TR2X/music/track24.flac
TR2X/music/track25.flac
TR2X/music/track26.flac
TR2X/music/track27.flac
TR2X/music/track28.flac
TR2X/music/track29.flac
TR2X/music/track30.flac
TR2X/music/track31.flac
TR2X/music/track32.flac
TR2X/music/track33.flac
TR2X/music/track34.flac
TR2X/music/track35.flac
TR2X/music/track36.flac
TR2X/music/track37.flac
TR2X/music/track38.flac
TR2X/music/track39.flac
TR2X/music/track40.flac
TR2X/music/track41.flac
TR2X/music/track42.flac
TR2X/music/track43.flac
TR2X/music/track44.flac
TR2X/music/track45.flac
TR2X/music/track46.flac
TR2X/music/track47.flac
TR2X/music/track48.flac
TR2X/music/track49.flac
TR2X/music/track50.flac
TR2X/music/track51.flac
TR2X/music/track52.flac
TR2X/music/track53.flac
TR2X/music/track54.flac
TR2X/music/track55.flac
TR2X/music/track56.flac
TR2X/music/track57.flac
TR2X/music/track58.flac
TR2X/music/track59.flac
TR2X/music/track60.flac
TR2X/music/track61.flac
TR2X/savegame.0
TR2X/savegame.1
TR2X/savegame.2
TR2X/savegame.3
TR2X/savegame.4
TR2X/savegame.5
TR2X/shaders/2d.glsl
TR2X/shaders/3d.glsl
TR2X/shaders/fade.glsl
TR2X/shaders/fbo.glsl
TR2X/TR2X
TR2X/TR2X.log

**Comment by rr-** [comment]
@Toumlab, I was able to replicate your issue, but only by intentionally making the `music` directory unreadable. Could you please verify that your user has permission to access the directory? A quick, though not the prettiest, solution is to run the command `chmod 0777 path/to/music`.

**Comment by Toumlab** [comment]
Sorry rr, it makes no difference for me...

**Comment by rr-** [comment]
@Toumlab I think we've got the bug down, thanks to a patch from MaxDiSaggio on Discord. Could you please test the build from https://github.com/LostArtefacts/TRX/pull/2526 to confirm? Thanks.

**Comment by Toumlab** [comment]
Hi rr!
Thanks for your dedication!
I've just tried version 0.9.1-25-g015b9d7: wow, sound is working great now, you're a genius!
You can close this bug report as everything is fine!
Thanks also for these two great programs!

**Comment by rr-** [comment]
Thanks for the quick reply, however all credit for this fix goes to MaxDiSaggio :)

**Comment by Toumlab** [comment]
Then many thanks to both of you for your help!
